import SiteShell from "@/app/site-shell";
export default function Page(){return <SiteShell><main className="page-wrap prose-page">
 <p className="eyebrow">HOW O CHECKS</p><h1 className="page-title">A clearer picture. Not a crystal ball.</h1>
 <section><h2>Start with identity</h2><p>A token name can be copied. OLWIF anchors a check to the full mint or contract address and a specific chain. A 0x address can exist on multiple networks; if detection is ambiguous, you must choose the network. A Pump.fun link is not itself proof that a token launched there.</p></section>
 <section><h2>Follow the evidence</h2><p>OLWIF brings together public blockchain records, token-security checks, market snapshots and project information where coverage is available. Directly reported code repositories are checked for public metadata. Reports retain project links and collection times, and make incomplete checks clear. Our <a className="inline-link" href="/terms#research-providers">terms describe the data providers</a>.</p></section>
 <section><h2>Public pages, brought into the report</h2><p>Each new check can read up to four public pages linked from returned token information or limited web-search results. Robots restrictions, login walls, unavailable pages and rate limits remain gaps; we do not bypass them.</p><p>OLWIF turns returned text into limited, rule-based notes: for example, whether the exact token address appears and whether documentation or repository links are present. This is not an AI verdict, a code audit or independent verification of a project’s claims. Page links, collection times and short page excerpts stay with the evidence.</p></section>
 <section><h2>Finding relevant pages</h2><p>An exact-address web search can help OLWIF discover pages connected to a token. Returned results are leads, not proof of ownership or authenticity. Only pages actually read contribute page-content notes; search-engine AI answers are not used.</p><p>Coverage depends on what is indexed and accessible when you ask. If a search cannot finish, the report keeps the other completed checks and clearly identifies the gap.</p></section>
 <section><h2>Five lenses, no magic safety score</h2><p>Identity asks whether the exact address was confirmed. Integrity summarises the contract and holder warnings returned. Project &amp; socials brings together reported accounts, public links and page-stated details. Momentum describes the indexed market snapshot. Trading activity shows actual buy and sell counts, volume and relevant holder warnings for the selected pool. Transactions are not unique traders. A passed check never cancels out unknowns.</p></section>
 <section><h2>Fresh when requested</h2><p>Checks run when you ask. A report less than one minute old may be reused with its original timestamp to protect public sources. Accounts can save reports, track manually entered holdings and request a watchlist check. Where background monitoring has been configured, a limited shared queue can also refresh watched tokens. Your account shows whether that service is active. Provider cache, queue and indexing delays mean this is not a tick-by-tick feed.</p><p>Alerts appear in your account inbox. Optional desktop notices require the account page to be open and refreshed; email and closed-browser push delivery are not supported. Monitoring checks token and market sources, not a continuous stream of websites or social posts.</p></section>
 <section><h2>The limits matter</h2><p>OLWIF does not read every website or social post, verify team identities, audit code, reconstruct complete creator history, or map all linked wallets, bundles and snipers. Public-page text is not a continuous social feed: follower authenticity, engagement quality and private discussions are not established. No public-source tool can guarantee access to every source. Missing information stays not verified.</p></section>
 <section><h2>How to read a warning</h2><p>Critical warning means a checked source reported a particularly serious condition, not that fraud has been legally established. Caution means there are findings to investigate. Not enough evidence means checks are incomplete, not that risk is low. Reports describe evidence and limitations rather than assigning an approval probability.</p></section>
 <section><h2>Independent of the token</h2><p>A Solana wallet can optionally sign a message to create or access an account. That sign-in does not authorise a transaction or give OLWIF spending access. OLWIF does not hold funds, buy tokens or place trades. Every token, including any future OLWIF token, is subject to the same evidence rules.</p><p>O’s celebration means the overall signal and all five categories are green in a recent report. It is not an endorsement, a safety guarantee or a prediction of returns. A report is research context for your own investigation, never a recommendation to buy, sell or copy a wallet.</p></section>
 <a className="inline-link" href="/">Back to search</a>
</main></SiteShell>;}
