import SiteShell from "@/app/site-shell";
export default function Page(){return <SiteShell><main className="page-wrap prose-page">
 <p className="eyebrow">PRIVACY · PRIVATE BETA</p><h1 className="page-title">Your research. Your choice.</h1>
 <section><h2>Optional private accounts</h2><p>Public token checks do not require a wallet. To create or sign in to a personal account, a supported Solana wallet signs a short-lived, single-use message tied to this website. We store the public wallet address, a hashed session token and necessary authentication records. We never request a seed phrase, private key, token approval or spending permission.</p><p>Your saved-report list, manually entered holdings, cost figures, watchlist and alert preferences are private to your account. Saving a public report does not make the underlying public report private. The account does not automatically import your wallet holdings.</p><p>You can remove individual items or delete your account data in account settings. Deletion removes private saved-report references, holdings, watchlists, preferences and inbox alerts and revokes account sessions; it does not erase public token reports or blockchain records. Expired sign-in records are cleaned during later sign-in attempts. Hosting backups and infrastructure logs may have separate retention periods that must be specified before public launch.</p></section>
 <section><h2>What a check sends</h2><p>The token address and chain are sent from this site’s server to relevant public-data providers. If optional web search is configured, the exact public token address is also sent to Tavily to find source leads. Up to four project or search-linked public-page URLs are sent to Jina Reader to retrieve their text. Those services process requests under their own policies.</p><p>We do not send your browser history, browser cookies, wallet credentials or private account sessions to these research providers. If you open a source, project or network link, you visit that third party under its own policies. Do not submit personal or secret information. A blockchain address can sometimes be linked to a person.</p></section>
 <section><h2>What we keep</h2><p>The application stores token evidence reports, their timestamps, source links and report visibility settings in its database. Public-page evidence includes short notes, retrieval status, source URLs and very short excerpts; full retrieved pages and full search-result snippets are not saved. The original pasted token URL is removed and the exact address is saved instead.</p><p>Saved reports are visible to people who can access this Site; if the Site later becomes public, visible reports would become public too. Hidden reports remain in storage for owner restoration.</p></section>
 <section><h2>Owner access</h2><p>The protected owner area uses ChatGPT sign-in. The hosting service forwards the authenticated identity. The application stores a stable owner identifier and uses the configured owner email for first-time authorisation. It does not collect your ChatGPT password. Optional API credentials stay on the server; they are not saved in public reports or the report database.</p></section>
 <section><h2>Cookies and logs</h2><p>OLWIF does not add advertising trackers or marketing analytics. Authentication and hosting may use necessary cookies and infrastructure logs. Site-wide request counters limit source usage; the application does not build an IP-based visitor profile.</p></section>
 <section><h2>Search, monitoring and notifications</h2><p>Public research runs on demand. Watched tokens can be checked on demand and, once hosted scheduling is enabled, through a limited shared background queue. Account settings show whether background checks are actually running. Monitoring sends public token identifiers to the enabled research providers, never private holdings, cost figures or wallet sign-in messages. Monitoring does not run a new public-web search on every update.</p><p>Optional web search uses an exact-address query, not a personal search profile. Search-provider AI answers are disabled. Site-wide request counters protect the service. Necessary sign-in abuse controls temporarily count attempts against hashed client IP addresses and public wallet addresses; they are not advertising profiles.</p><p>Alerts stay in your account inbox and are removed after 30 days during subsequent monitoring runs, or when you delete your account. Optional desktop notices require your browser permission and this account page to be open and refreshed; this release does not send email or closed-browser push notifications. Quiet hours mute desktop notices, not inbox records. Reports and owner settings remain until the operator removes them; hiding is not deletion. Third-party services have separate retention policies.</p></section>
 <section><h2>Before public launch</h2><p>This private beta does not yet publish a business identity, privacy contact or final retention policy. These need to be added before inviting public users. The owner can manage report visibility from the Owner’s desk. The privacy notice should be legally reviewed for the final service.</p></section>
 <a className="inline-link" href="/">Back to search</a>
</main></SiteShell>;}
