"use client";
import {useState} from "react";import SiteShell from "./site-shell";import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";import {Button} from "@/components/ui/button";import {ExternalLink,RefreshCw,Copy,Download,ArrowLeft,Check} from "lucide-react";import {safeLink} from "@/lib/security";import {tokenSupply,taxPercent} from "@/lib/format";
import ReportVerdict from "@/components/report-verdict";
import AssessmentCard from "@/components/assessment-card";
import ReportSources, {plainCheckFinding} from "@/components/report-sources";
import PublicWebResearch from "@/components/public-web-research";
import ProjectProfile from "@/components/project-profile";
import ProsCons from "@/components/pros-cons";
import SaveToAccount from "@/components/save-to-account";
import ReportCelebration from "@/components/report-celebration";
import {presentResearchReport} from "@/lib/research/report-presentation.js";
import {displayLinkLabel} from "@/lib/research/link-label.js";
// Provider data is rendered only as escaped text and allowlisted-link protocols.
type Item=Record<string,any>;
function date(value:unknown){const n=typeof value==="number"?value:Date.parse(String(value));return Number.isFinite(n)?new Date(n).toISOString().replace("T"," ").slice(0,19)+" UTC":"Not verified";}
function number(value:unknown,suffix=""){return typeof value==="number"&&Number.isFinite(value)?value.toLocaleString("en-GB",{maximumFractionDigits:2})+suffix:"Not verified";}
function money(value:unknown){return typeof value==="number"&&Number.isFinite(value)?new Intl.NumberFormat("en-GB",{style:"currency",currency:"USD",maximumFractionDigits:value!==0&&Math.abs(value)<.01?8:2}).format(value):"Not verified";}
function LinkOut({url,children}:{url:unknown,children:React.ReactNode}){const href=safeLink(url);return href?<a className="inline-link external" href={href} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={13}/></a>:<span>{children}</span>;}
function Fact({label,value}:{label:string,value:React.ReactNode}){return <div className="fact"><dt>{label}</dt><dd>{value??"Not verified"}</dd></div>;}
export default function ReportView({report:originalReport,id}:{report:Item,id:string}){
 const r=presentResearchReport(originalReport);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[copied,setCopied]=useState(false);
 const m=r.metrics||{},research=r.research||{},sources=r.sources||[],links=research.links||[];
 const coinGeckoCredit=(originalReport.sources||[]).some((s:Item)=>s.ok===true&&["GeckoTerminal market","GeckoTerminal metadata"].includes(s.name))||originalReport.research?.market?.provider==="GeckoTerminal"||originalReport.research?.market?.corroboration?.provider==="GeckoTerminal";
 const completed=sources.filter((s:Item)=>s.ok).length;
 async function refresh(){setBusy(true);setMessage("");try{const response=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:r.target.address,chain:r.target.chain})});const result=await response.json() as Record<string,any>;if(!response.ok)throw new Error(result.error);if(result.id===id)setMessage("This report is less than one minute old. Try again after its cache window.");else window.location.assign("/report/"+result.id);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function download(){const clean={...originalReport};delete clean.riskScore;delete clean.confidence;delete clean.tier;const url=URL.createObjectURL(new Blob([JSON.stringify(clean,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="olwif-"+r.target.address+".json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <SiteShell><main className="page-wrap"><a className="back-link" href="/"><ArrowLeft size={16}/>Check another token</a><div className="report-heading"><div><p className="eyebrow">O’S RESEARCH NOTES</p><h1 className="page-title">{r.identity.name||"Unnamed token"} <span>{r.identity.symbol||""}</span></h1><div className="row"><span className="tag">{r.identity.chain||r.target.chain}</span><span className="small muted">Checked {date(r.generatedAt)}</span></div></div><img className="report-owl" src="/o-owl.png" alt="O has taken a look" width={115} height={120}/></div>
 <div className="address-strip"><code>{r.target.address}</code><Button variant="ghost" size="sm" aria-label="Copy token address" onClick={async()=>{try{await navigator.clipboard.writeText(r.target.address);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setMessage("Copy is unavailable in this browser. Select the address instead.");}}}>{copied?<Check size={16}/>:<Copy size={16}/>}</Button></div>
 <div className="row spread report-actions"><p className="small muted">One exact address. {completed}/{sources.length} token-data checks returned data.<br/>Coverage is not a safety score.</p><div className="row"><SaveToAccount reportId={id}/><Button variant="outline" onClick={download}><Download size={16}/>Download</Button><Button onClick={refresh} disabled={busy}><RefreshCw size={16} className={busy?"spin":""}/>{busy?"Checking…":"Refresh check"}</Button></div></div>
 <ReportCelebration report={originalReport} id={id}/>
 {message&&<p role="status" className="notice">{message}</p>}
 <div id="report-summary"><ReportVerdict report={r} reportId={id}/></div>
 <div className="assessment-grid">{(research.assessments||[]).map((a:Item)=><AssessmentCard key={a.name} assessment={{name:a.name,status:a.status,summary:a.summary}} report={r} reportId={id}/>)}</div>
 <Tabs defaultValue="overview"><TabsList className="report-tabs" aria-label="Report sections"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="people">People &amp; project</TabsTrigger><TabsTrigger value="onchain">On-chain</TabsTrigger><TabsTrigger value="market">Market</TabsTrigger><TabsTrigger value="sources">Checks &amp; gaps</TabsTrigger></TabsList>
 <TabsContent value="overview"><ProsCons report={originalReport} reportId={id}/><section className="panel"><h2>Project links, in one place</h2><p className="muted">These links are not independently authenticated as official. Check the exact mint on each destination. Supporting evidence is in Checks &amp; gaps.</p><div className="link-grid">{links.filter((link:Item)=>link.kind!=="risk").map((link:Item)=><div className="link-item" key={link.url}><span className="tag">{link.kind}</span><LinkOut url={link.url}>{link.kind==="market"?"Market chart":displayLinkLabel(link)}</LinkOut></div>)}</div></section></TabsContent>
 <TabsContent value="people"><section className="panel"><h2>Who made it?</h2><dl className="facts"><Fact label="Reported creator / deployer" value={research.creator?.address?<LinkOut url={research.creator.url}><span className="mono">{research.creator.address}</span></LinkOut>:"Not verified"}/><Fact label="Creator’s recent transactions" value={number(research.creator?.recentTransactions)}/><Fact label="Prior contract creations in returned history" value={number(research.creator?.recentContractCreations)}/><Fact label="Developer holdings" value={number(m.developerHoldingsPct,"%")}/><Fact label="Selected pool created" value={date(m.pairCreatedAt)}/></dl><p className="notice">{research.creator?.historyCoverage}. A wallet is not a verified person. Pool age is not the token’s creation date.</p>{research.creator?.previousContracts?.map((x:Item)=><p key={x.address}><LinkOut url={x.url}><span className="mono">{x.address}</span></LinkOut> · {date(x.timestamp)}</p>)}</section>
 <ProjectProfile report={originalReport}/>
 <section className="panel"><h2>Code &amp; development</h2><p className="muted">{research.repositoryCoverage}</p>{(research.repositories||[]).map((repo:Item)=><div className="repo" key={repo.url}><h3><LinkOut url={repo.url}>{repo.name}</LinkOut></h3><p>{repo.description}</p><dl className="facts"><Fact label="Created" value={date(repo.createdAt)}/><Fact label="Last push" value={date(repo.pushedAt)}/><Fact label="Archived" value={repo.archived?"Yes":"No"}/><Fact label="Fork" value={repo.fork==null?"Not verified":repo.fork?"Yes":"No"}/></dl><p className="small muted">Reported repository; ownership and code quality are not verified.</p></div>)}</section>
 <PublicWebResearch report={originalReport}/></TabsContent>
 <TabsContent value="onchain"><section className="panel"><h2>Token structure &amp; control</h2><dl className="facts"><Fact label="Supply" value={tokenSupply(m.totalSupply??m.supply,m.decimals)}/><Fact label="Decimals" value={number(m.decimals)}/><Fact label="Mint authority" value={m.mintAuthorityStatus||m.mintAuthority||"Not verified"}/><Fact label="Freeze authority" value={m.freezeAuthorityStatus||m.freezeAuthority||"Not verified"}/><Fact label="Liquidity lock reported" value={number(m.lpLockedPct,"%")}/><Fact label="Insider percentage reported" value={number(m.insiderPercentage,"%")}/><Fact label="Buy tax reported" value={number(taxPercent(m.buyTax),"%")}/><Fact label="Sell tax reported" value={number(taxPercent(m.sellTax),"%")}/></dl></section>
 <section className="panel"><h2>Holders &amp; concentration</h2><dl className="facts"><Fact label="Holder count" value={number(m.holders)}/><Fact label="Largest holder" value={number(m.topHolderPct,"%")}/><Fact label="Top 10 combined" value={number(m.top10Pct,"%")}/></dl><p className="small muted">{m.holdersNote?.replace("uses the named source", "uses the snapshot identified in Checks & gaps")||"Snapshots may include pool, vault and contract accounts. These are not necessarily individual people."}</p>{(m.topHolders||[]).length>0&&<div className="table-scroll"><table><thead><tr><th>Address</th><th>Share</th><th>Account type</th></tr></thead><tbody>{m.topHolders.map((h:Item)=><tr key={h.address}><td><LinkOut url={h.url}><span className="mono">{h.address}</span></LinkOut></td><td>{number(h.percentage,"%")}</td><td>{h.kind||"Not verified"}</td></tr>)}</tbody></table></div>}<p className="notice">Linked wallets, bundles, snipers and historic wallet profitability are not established by this report. A dispersed holder list does not prove independent ownership.</p></section>
 <section className="panel"><h2>Detailed findings</h2><div className="stack">{(r.findings||[]).map(plainCheckFinding).map((f:Item,i:number)=><div className={"finding "+(f.code==="RUGCHECK_NO_LISTED_RISKS"&&!f.hardFail?"info":f.severity)} key={i}><strong>{f.hardFail?"Critical warning":f.code==="RUGCHECK_NO_LISTED_RISKS"?"Limited check":f.severity==="good"?"Check passed":f.severity==="unknown"?"Not verified":f.severity==="info"?"Context":"Warning"} · {f.title}</strong><p>{f.detail}</p><small>{f.category}</small></div>)}</div></section></TabsContent>
 <TabsContent value="market"><section className="panel"><div className="row spread"><h2>A moment in the market</h2><LinkOut url={research.market?.poolUrl}>Open chart</LinkOut></div><p className="muted">Largest returned pool; not total cross-pool liquidity or an executable quote. Snapshot details are in Checks &amp; gaps.</p><dl className="facts"><Fact label="Price" value={money(m.priceUsd)}/><Fact label="Market cap" value={money(m.marketCap)}/><Fact label="Fully diluted value" value={money(m.fdv)}/><Fact label="Pool liquidity" value={money(m.liquidityUsd)}/><Fact label="24-hour volume" value={money(m.volume24h)}/><Fact label="Selected pool created" value={date(m.pairCreatedAt)}/></dl><div className="table-scroll"><table><thead><tr><th>Window</th><th>Volume</th><th>Buys</th><th>Sells</th><th>Transactions</th><th>Price change</th></tr></thead><tbody>{(research.market?.windows||[]).map((w:Item)=><tr key={w.window}><td>{w.window}</td><td>{money(w.volumeUsd)}</td><td>{number(w.buys)}</td><td>{number(w.sells)}</td><td>{number(w.transactions)}</td><td>{number(w.priceChangePct,"%")}</td></tr>)}</tbody></table></div><p className="notice">Volume and buy counts can be manipulated. This snapshot cannot establish organic demand, predict returns or guarantee that you can sell.</p></section></TabsContent>
 <TabsContent value="sources"><ReportSources report={originalReport}/></TabsContent>
 </Tabs>{coinGeckoCredit&&<p className="small muted">On-chain data · <a className="inline-link" href="https://www.coingecko.com/en/api" target="_blank" rel="noopener noreferrer">Powered by CoinGecko</a></p>}</main></SiteShell>;
}
